name: worktrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8

  # Add the camera package for camera functionality
  camera: ^0.10.0+1
  
  # Path for handling files and directories
  path_provider: ^2.0.14

  # Image picker for picking images from gallery/camera (optional)
  image_picker: ^0.8.7+3

  # MLKit for on-device face recognition (optional depending on your needs)
  google_ml_kit: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - img/img1.png
    - img/logo.png
    - img/camera.png

  # Add any custom fonts if needed, e.g.:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
